#!/bin/bash

set -e

yarn link

echo Creating...
rm -rf test/sandbox
mkdir test/sandbox
PACKAGE=`cat <<EOF
{
  "name": "foobar",
  "devDependencies": {
    "modern-node": "*"
  }
}
EOF
`
echo "$PACKAGE" > test/sandbox/package.json

rm -rf test/sandbox-ts
mkdir test/sandbox-ts
PACKAGE=`cat <<EOF
{
  "name": "foobar",
  "devDependencies": {
    "modern-node": "*",
    "typescript": "*"
  }
}
EOF
`
echo "$PACKAGE" > test/sandbox-ts/package.json

echo Running...
SCRIPT=`cat <<EOF
const path = require('path');
const root = path.resolve(__dirname, 'test/sandbox');
const appName = 'sandbox';
const verbose = false;
const originalDirectory = path.resolve(__dirname);
const template = null;
const data = [root, appName, verbose, originalDirectory, template];
var init = require('./src/init.js');
const result = init.apply(null, data);
EOF
`
node -e "$SCRIPT"

SCRIPT=`cat <<EOF
const path = require('path');
const root = path.resolve(__dirname, 'test/sandbox-ts');
const appName = 'sandbox';
const verbose = false;
const originalDirectory = path.resolve(__dirname);
const template = null;
const data = [root, appName, verbose, originalDirectory, template];
var init = require('./src/init.js');
const result = init.apply(null, data);
EOF
`
node -e "$SCRIPT"

echo Linking...
(cd test/sandbox && yarn link modern-node)

echo Linking...
(cd test/sandbox-ts && yarn link modern-node)
